# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 757260c0ee7f23dc787a444e1682c64e569998f085083f3b01ce379159a055347f67e4f403d36d4a6e9ebeb3aa487e784e55c05bdea69afd097e2cd0a7aea2a7

test:
  secret_key_base: 9fb2c266afc9066b779c21b328fae236becfaae0b6a47fdbc6561ee129c0898c9d58ee43e921643f6f64576bfd8d86e46e2ba8be281899bfc570d6b1dc09faa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
